# Generated by Django 5.2.11 on 2026-02-25 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Watering Date')),
                ('method', models.CharField(choices=[('Top', 'Top Watered'), ('Botton', 'Bottom Watered'), ('Mist', 'Misted')], default='Top', max_length=10)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waterings', to='main_app.plant')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
