# Generated by Django 5.2.11 on 2026-02-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_watering'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='fertilizers',
            field=models.ManyToManyField(to='main_app.fertilizer'),
        ),
    ]
